dbVenta-cnx: server=localhost;Database=db_venta;User Id=SA;Password=sql2016.;TrustServerCertificate=True;
url-base-servicio-stock: https://localhost:7065
log-mongo-server-db: mongodb://localhost:27017/dbLogs
log-mongo-db-collection: logs-ventas
url-base-servicio-pago: https://localhost:7065
